spring.application.name=attendance-service
spring.datasource.url=jdbc:postgresql://localhost:5432/vulcandb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:kelvin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083
services.worker.url=http://localhost:8082
services.auth.url=http://localhost:8081
services.payroll.url=http://localhost:8086
services.ai.url=http://localhost:9000