spring.application.name=analytics-service
spring.datasource.url=jdbc:postgresql://localhost:5432/vulcandb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:kelvin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088

# URLs of other services
services.auth.url=http://localhost:8081
services.worker.url=http://localhost:8082
services.attendance.url=http://localhost:8083
services.equipment.url=http://localhost:8084
services.task.url=http://localhost:8085
services.payroll.url=http://localhost:8086
services.survey.url=http://localhost:8087