spring.application.name=worker-service
spring.datasource.url=jdbc:postgresql://localhost:5432/vulcandb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:kelvin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082